config/routes.rb
Rails.application.routes.draw do
  root to: "welcome#index"

  devise_for :users

  resources :users, only: [:show]
  resources :games, only: [:show, :create]

  resources :games, only: [] do
    resources :card_sets, only: [:create]
    resources :assignments, only: [:update]
    post 'check_board', to: 'games#check_board'
    post 'give_hint',   to: 'games#give_hint'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :game
  belongs_to :card
  belongs_to :card_set, optional: true
  scope :remaining, -> { where(card_status: 'remaining') }
  scope :in_play, -> { where(card_status: 'in_play') }
  scope :in_set, -> { where(card_status: 'in_set') }
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :assignments
  has_many :games, through: :assignments
  has_many :card_sets, through: :assignments
end

app/models/card_set.rb
class CardSet < ApplicationRecord
  has_many :assignments
  has_many :games, through: :assignments
  has_many :cards, through: :assignments
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  has_many :assignments
  has_many :cards, through: :assignments
  has_many :card_sets, through: :assignments

  ATTRS = ["shape", "color", "shade", "number"]

  # No cards left in deck and no sets available
  def over?
    self.assignments.remaining.count == 0 && !sets_available?
  end

  # call this when you press the button to check for sets
  def update_board
    if !sets_available?
      add_three_cards
      return true
    else
      return false
    end
  end

  # checks remaining cards and update 1st 3 to in_play
  def add_three_cards
    cards = self.assignments.remaining.first(3)
    cards.each do |card|
      card.update_attribute(:card_status, "in_play")
    end
  end

  def sets_available?
    # sets all possible combos
    combos = combos(self.assignments.in_play)
    # goes thu each set of possible cards
    combos.each do |assign_set|
      cards = []
      # goes through each assigned_set of possible cards
      assign_set.each do |assign|
        # adds the actual cards to a cards array
        # we now have an array of actual cards to check
        cards << assign.card
      end
      return true if match(cards)
    end
    false
  end

  # returns all possible 3 card combos
  def combos(cards)
    cards.to_a.combination(3).to_a
  end

  def match(cards)
    # loops through the attributes
    ATTRS.each do |attr|
      return false if !attr_set?(cards, attr)
    end
    true
  end

  def hint
    combos(self.assignments.in_play).each do |combo|
    end
    if sets_available?
      combos = combos(self.assignments.in_play)
      combos.each do |assign_set|
        cards = []
        assign_set.each do |assign|
          cards << assign.card
        end
      return cards
      end
    end
  end

  # given an attribute and cards
  # checks each card for that attribute
  # pushes the attribute in the array
  # then checks if they're all the same or different
  def attr_set?(cards, attr)
    array = []
    cards.each do |card|
      # evalutes the string 'attr' and returns the value
      array << card.send(attr)
    end

    # only return true if it's all the same or totally different
    return true if array.uniq.count == 1
    return true if array.uniq.count == 3
    return false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :games
  has_many :assignments, through: :games
  has_many :card_sets, through: :assignments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:username, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password) }
        end

end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController

end

app/controllers/card_sets_controller.rb
class CardSetsController < ApplicationController
  def create
    @game = Game.find(params[:game_id])

    respond_to do |format|
      format.html { redirect_to game_path(@game) }
      format.json {
        card1 = Card.find_by(image_url: (params["cards"]["c1"].downcase.split(" ").join("_") + ".png"))
        card2 = Card.find_by(image_url: (params["cards"]["c2"].downcase.split(" ").join("_") + ".png"))
        card3 = Card.find_by(image_url: (params["cards"]["c3"].downcase.split(" ").join("_") + ".png"))

        cards = [card1, card2, card3]

        if @game.match(cards)

          new_card_set = CardSet.create

          cards_in_new_set = []

          cards.each do |card|
            Assignment.find_by_card_id_and_game_id(card.id, @game.id).update(card_status: "in_set", card_set_id: new_card_set.id)
          end

          deck = @game.assignments.remaining

          new_cards = deck.sample(3)

          new_cards.each do |assignment|
            assignment.update(card_status: "in_play")
          end

          new_cards_json = {
            "1": "<img src='../assets/#{new_cards[0].card.image_url}' alt='#{new_cards[0].card.image_url.split(".").first.split("_").join(" ")}'>",
            "2": "<img src='../assets/#{new_cards[1].card.image_url}' alt='#{new_cards[1].card.image_url.split(".").first.split("_").join(" ")}'>",
            "3": "<img src='../assets/#{new_cards[2].card.image_url}' alt='#{new_cards[2].card.image_url.split(".").first.split("_").join(" ")}'>",
            "set_1": "<img src='../assets/#{params['cards']['c1'].downcase.split(' ').join('_')}' alt='#{params["cards"]["c1"]}'>",
            "set_2": "<img src='../assets/#{params['cards']['c2'].downcase.split(' ').join('_')}' alt='#{params["cards"]["c2"]}'>",
            "set_3": "<img src='../assets/#{params['cards']['c3'].downcase.split(' ').join('_')}' alt='#{params["cards"]["c3"]}'>"
          }

          @response = new_cards_json.to_json

          render json: @response
        else
          redirect_to game_path(@game.id)
          flash.notice = 'Not a valid set'
        end
      }
    end
  end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def show
    @game = Game.find(params[:id])
    @board = @game.assignments.in_play
  end

  def create
    game = Game.new(user_id: current_user.id)

    if game.save
      cards = Card.all
      board = cards.sample(12)
      deck = []

      cards.each do |card|
        if !board.include?(card)
          deck << card
        end
      end

      board.each do |card|
        game.assignments.create!(card_id: card.id, card_status: "in_play")
      end

      deck.each do |card|
        game.assignments.create!(card_id: card.id, card_status: "remaining")
      end

      redirect_to game_path(game)
    else
      redirect_to root_path
    end
  end

  def check_board
    @game = Game.find(params[:game_id])

    if @game.update_board
      redirect_to game_path(@game)
    else
      flash[:alert] = "There are valid sets on the board. Keep trying! Here's a hint:"
      redirect_to game_path(@game)
    end
  end

  def give_hint
    @game = Game.find(params[:game_id])

    respond_to do |format|
      format.html { redirect_to game_path(@game) }
      format.js {@combo = @game.hint}
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def new
  end

  def show
    @games = User.find(params[:id]).games
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/card_sets_helper.rb
module CardSetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/games/give_hint.js.erb
$("#<%= j @combo.sample.id.to_s %>").find("img").addClass("active")

app/views/games/show.html.erb
<% if flash[:alert] %>
  <div class="notice"><%= flash[:alert] %></div>
<% end %>

<div class="board">
  <% @board.each do |assignment| %>
    <div class="card-in-play" id="<%= assignment.card.id %>">
      <%= image_tag assignment.card.image_url %>
    </div>
  <% end %>

  <div class="check-board">
    <%= form_for Game.new, url: game_check_board_path(@game.id) do |f| %>
      <%= f.submit('Sets on Board?', class: "check-game-button") %>
    <% end %>
  </div>

  <div class="add-hint">
    <%= form_for Game.new, url: game_give_hint_path(@game.id), locals: {card: @card}, remote: true do |f| %>
      <%= f.submit('Hint', class: "hint-button") %>
    <% end %>
  </div>

  <div class="sets-played">
    <h2>Sets Played:</h2>
    <%= render 'shared/found_cards' %>
  </div>
</div>

<div class="side-bar">
  <div class="deck-count">
    <h2><%= @game.assignments.remaining.count %></h2>
    <h3>Cards Remaining</h3>
    <h3>in the Deck</h3>
  </div>
  <div class="timer-box">
    <div id="timer">00:00</div>
      <!-- <div class="controls"> -->
      <!-- <div class="btn" id="start">Start</div> -->
      <div class="btn" id="stop">Stop</div>
      <!-- <div class="btn" id="reset">Reset</div> -->
    </div>
  </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HawkSet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <header>
      <ul class="nav">
        <li><%= link_to image_tag("logo.png", border: 0, class: "logo"), root_path %></li>
        <% if user_signed_in? %>
          <!-- THIS NEEDS TO GO TO 'USER_PATH' WHEN ITS READY -->
          <li><%= link_to "Logout", destroy_user_session_path, {method: :delete} %></li>
          <li><%= link_to current_user.username, current_user %></li>
        <% else %>
          <li><%= link_to "Login", user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>

        <div class="new-game" id="start-timer">
          <% if current_user %>
            <li>
              <%= form_for Game.new, url: games_path do |f| %>
                <%= f.submit('New Game', class: "new-game-button") %>
              <% end %>
            </li>
          <% end %>
        </div>
      </ul>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_found_cards.html.erb
<% @game = Game.find_by_user_id(current_user.id) %>
<% @game.card_sets.each do |set| %>
  <% set.cards.pluck(:image_url).each_slice(3) do |img| %>
    <table>
      <tr>
        <td> <%= image_tag img[0], class: "img_set_card" %></td>
        <td> <%= image_tag img[1], class: "img_set_card" %></td>
        <td> <%= image_tag img[2], class: "img_set_card" %></td>
      </tr>
    </table>
  <% end %>
<% end %>

app/views/shared/_game_rules.html.erb
<h3>Rules to play</h3>
<div>
  <p> Goal: Race against the clock to select as many valid sets as you can, as quickly as possible.</p>

  <p> Card Attributes: Color, Shape, Shading, and Shape Count.</p>

  <p>How to Make a Set:
  1) Select three cards with no matching attributes.
  2) Select three cards with as many matching attributes as you want, BUT that attribute must be present across all three selected cards.</p>

  <p>Rule #1: A set can not contain only two cards with a matching attribute. All three cards must have that attribute or only one may have it.</p>

  <p>Game Over: The game is over when there are no more cards left in the deck, and there are no more sets available on the board.</p>

  <p>Hints: If there are no more sets on the current board, but still cards in the deck, we will give you three more cards.</p>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<h1><%= @user.username %>'s Result</h1>

<% @user.games.each do |game| %>
  <h3><%= game.card_sets.count %> Sets </h3>
  <h3>in</h3>
  <h3><%= game.total_play_time %></h3>
  <div id="found_cards">
    <%= render 'shared/found_cards' %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%= render "shared/game_rules" %>